parameters:
  _param:
    kubernetes_calico_calicoctl_repo: ${_param:mcp_docker_registry}/mirantis/projectcalico/calico
    kubernetes_calico_repo: ${_param:mcp_docker_registry}/mirantis/projectcalico/calico
    kubernetes_calico_cni_repo: ${_param:mcp_docker_registry}/mirantis/projectcalico/calico
    kubernetes_calico_kube_ctl_repo: ${_param:mcp_docker_registry}/mirantis/projectcalico/calico
    kubernetes_hyperkube_repo: ${_param:mcp_docker_registry}/mirantis/kubernetes
    kubernetes_contrail_cni_repo: ${_param:mcp_docker_registry}/mirantis/kubernetes
    kubernetes_contrail_network_controller_repo: ${_param:mcp_docker_registry}/mirantis/kubernetes/contrail-integration
    kubernetes_netchecker_agent_repo: mirantis
    kubernetes_netchecker_server_repo: mirantis
    kubernetes_virtlet_repo: mirantis
    kubernetes_kubedns_repo: gcr.io/google_containers
    kubernetes_externaldns_repo: ${_param:mcp_docker_registry}/mirantis/external-dns
    kubernetes_genie_repo: https://docker-prod-local.artifactory.mirantis.com/artifactory/binary-prod-local/mirantis/kubernetes/cni-genie
    kubernetes_flannel_repo: quay.io/coreos
    kubernetes_metallb_repo: ${_param:mcp_docker_registry}/mirantis/metallb
    kubernetes_sriov_repo: https://docker-prod-local.artifactory.mirantis.com/artifactory/binary-prod-local/mirantis/kubernetes/sriov-cni
    kubernetes_cniplugins_repo: https://docker-prod-local.artifactory.mirantis.com/artifactory/binary-prod-local/mirantis/kubernetes/containernetworking-plugins
    kubernetes_dashboard_repo: ${_param:mcp_docker_registry}/mirantis/kubernetes
    kubernetes_coredns_repo: ${_param:mcp_docker_registry}/mirantis/coredns
    kubernetes_ingressnginx_repo: ${_param:mcp_docker_registry}/mirantis/kubernetes-ingress-nginx
    kubernetes_corends_etcd_operator_repo: quay.io/coreos
    kubernetes_containerd_repo: https://github.com/kubernetes-sigs/cri-tools/releases/download

    # component docker images
    kubernetes_docker_package: docker-engine=1.13.1-0~ubuntu-xenial
    kubernetes_calico_calicoctl_image: ${_param:kubernetes_calico_calicoctl_repo}/ctl:v3.1.3
    kubernetes_calico_image: ${_param:kubernetes_calico_repo}/node:v3.1.3
    kubernetes_calico_cni_image: ${_param:kubernetes_calico_cni_repo}/cni:v3.1.3
    kubernetes_calico_kube_controllers_image: ${_param:kubernetes_calico_kube_ctl_repo}/kube-controllers:v3.1.3
    kubernetes_hyperkube_image: ${_param:kubernetes_hyperkube_repo}/hyperkube-amd64:v1.11.3-2
    kubernetes_pause_image: ${_param:kubernetes_hyperkube_repo}/pause-amd64:v1.11.3-2
    kubernetes_contrail_cni_image: ${_param:kubernetes_contrail_cni_repo}/contrail-cni:v1.2.0
    kubernetes_contrail_network_controller_image: ${_param:kubernetes_contrail_network_controller_repo}/contrail-network-controller:v1.2.0
    kubernetes_virtlet_image: ${_param:kubernetes_virtlet_repo}/virtlet:v1.4.1
    kubernetes_criproxy_version: v0.12.0
    kubernetes_criproxy_checksum: md5=371cacd3d8568eb88425498b48a649dd
    kubernetes_netchecker_agent_image: ${_param:kubernetes_netchecker_agent_repo}/k8s-netchecker-agent:v1.2.2
    kubernetes_netchecker_server_image: ${_param:kubernetes_netchecker_server_repo}/k8s-netchecker-server:v1.2.2
    kubernetes_kubedns_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-kube-dns-amd64:1.14.5
    kubernetes_dnsmasq_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-dnsmasq-amd64:1.14.5
    kubernetes_sidecar_image: ${_param:kubernetes_kubedns_repo}/k8s-dns-sidecar-amd64:1.14.5
    kubernetes_dns_autoscaler_image: ${_param:kubernetes_kubedns_repo}/cluster-proportional-autoscaler-amd64:1.0.0
    kubernetes_externaldns_image: ${_param:kubernetes_externaldns_repo}/external-dns:v0.5.6-2
    kubernetes_genie_source: ${_param:kubernetes_genie_repo}/genie_v1.0-165-gbe0268b
    kubernetes_genie_source_hash: md5=20da66e80eaa453461cf269bf793f2aa
    kubernetes_flannel_image: ${_param:kubernetes_flannel_repo}/flannel:v0.10.0-amd64
    kubernetes_metallb_controller_image: ${_param:kubernetes_metallb_repo}/controller:v0.7.3-2
    kubernetes_metallb_speaker_image: ${_param:kubernetes_metallb_repo}/speaker:v0.7.3-2
    kubernetes_sriov_source: ${_param:kubernetes_sriov_repo}/sriov_v0.3-9-g3b31f1a
    kubernetes_sriov_source_hash: md5=cd9ea01e80d260218260314447c23b30
    kubernetes_cniplugins_source: ${_param:kubernetes_cniplugins_repo}/containernetworking-plugins_v0.7.2-96-g8bc4cc0.tar.gz
    kubernetes_cniplugins_source_hash: md5=1beef018ea8988f53356314ed020fefa
    kubernetes_dashboard_image: ${_param:kubernetes_dashboard_repo}/kubernetes-dashboard-amd64:v1.10.0-4
    kubernetes_telegraf_image: ${_param:mcp_docker_registry}/openstack-docker/telegraf:2018.8.0
    kubernetes_coredns_image: ${_param:kubernetes_coredns_repo}/coredns:v1.2.2-12
    kubernetes_ingressnginx_controller_image: ${_param:kubernetes_ingressnginx_repo}/nginx-ingress-controller-amd64:nginx-0.19.0-1
    kubernetes_corends_etcd_operator_image: ${_param:kubernetes_corends_etcd_operator_repo}/etcd-operator:v0.9.2
    kubernetes_containerd_source: ${_param:kubernetes_containerd_repo}/v1.12.0/crictl-v1.12.0-linux-amd64.tar.gz
    kubernetes_containerd_source_hash: md5=ff60b9ddfa5617f7ed14b3f3b6a60056

    kubelet_fail_on_swap: true
    kubernetes_dashboard_enabled: true
    kubernetes_kubedns_enabled: false
    kubernetes_externaldns_enabled: false
    kubernetes_coredns_enabled: true
    kubernetes_externaldns_provider: coredns
    kubernetes_virtlet_enabled: false
    kubernetes_virtlet_use_apparmor: false
    kubernetes_flannel_enabled: false
    kubernetes_genie_enabled: false
    kubernetes_calico_enabled: false
    kubernetes_opencontrail_enabled: false
    kubernetes_contrail_network_controller_enabled: false
    kubernetes_metallb_enabled: false
    kubernetes_sriov_enabled: false
    kubernetes_telegraf_enabled: false
    kubernetes_ingressnginx_enabled: false
    kubernetes_containerd_enabled: false

    kubernetes_ingressnginx_controller_replicas: 1

    # telegraf stuff
    kubernetes_telegraf_namespace: stacklight
    kubernetes_telegraf_resources_limits_memory: 500Mi
    kubernetes_telegraf_resources_requests_memory: 500Mi
    kubernetes_telegraf_agent_interval: 15
    kubernetes_telegraf_agent_round_interval: false
    kubernetes_telegraf_agent_metric_batch_size: 1000
    kubernetes_telegraf_agent_metric_buffer_limit: 10000
    kubernetes_telegraf_agent_collection_jitter: 2
    kubernetes_telegraf_agent_flush_interval: 10
    kubernetes_telegraf_agent_flush_jitter: 2
    kubernetes_telegraf_agent_precision: ms
    kubernetes_telegraf_agent_logfile: etc/telegraf/log
    kubernetes_telegraf_agent_debug: false
    kubernetes_telegraf_agent_quiet: false
    kubernetes_telegraf_agent_omit_hostname: false

  docker:
    host:
      pkgs:
        - ${_param:kubernetes_docker_package}
        - python-docker
      options:
        bip: 172.31.255.1/24
        storage-driver: overlay2

  kubernetes:
    common:
      containerd:
        enabled: ${_param:kubernetes_containerd_enabled}
        crictl:
          source: ${_param:kubernetes_containerd_source}
          hash: ${_param:kubernetes_containerd_source_hash}
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
        pause_image: ${_param:kubernetes_pause_image}
      cni:
        plugins:
          source: ${_param:kubernetes_cniplugins_source}
          hash: ${_param:kubernetes_cniplugins_source_hash}
      addons:
        dashboard:
          enabled: ${_param:kubernetes_dashboard_enabled}
          image: ${_param:kubernetes_dashboard_image}
        dns:
          enabled: ${_param:kubernetes_kubedns_enabled}
          kubedns_image: ${_param:kubernetes_kubedns_image}
          dnsmasq_image: ${_param:kubernetes_dnsmasq_image}
          sidecar_image: ${_param:kubernetes_sidecar_image}
          autoscaler:
            image: ${_param:kubernetes_dns_autoscaler_image}
        externaldns:
          enabled: ${_param:kubernetes_externaldns_enabled}
          namespace: kube-system
          image: ${_param:kubernetes_externaldns_image}
          provider: ${_param:kubernetes_externaldns_provider}
        coredns:
          enabled: ${_param:kubernetes_coredns_enabled}
          image: ${_param:kubernetes_coredns_image}
          etcd:
            operator_image: ${_param:kubernetes_corends_etcd_operator_image}
        contrail_network_controller:
          enabled: ${_param:kubernetes_contrail_network_controller_enabled}
          image: ${_param:kubernetes_contrail_network_controller_image}
        flannel:
          image: ${_param:kubernetes_flannel_image}
        telegraf:
          enabled: ${_param:kubernetes_telegraf_enabled}
          image: ${_param:kubernetes_telegraf_image}
          resources:
            limits:
              memory: ${_param:kubernetes_telegraf_resources_limits_memory}
            requests:
              memory: ${_param:kubernetes_telegraf_resources_requests_memory}
          agent:
            interval: ${_param:kubernetes_telegraf_agent_interval}
            round_interval: ${_param:kubernetes_telegraf_agent_round_interval}
            metric_batch_size: ${_param:kubernetes_telegraf_agent_metric_batch_size}
            metric_buffer_limit: ${_param:kubernetes_telegraf_agent_metric_buffer_limit}
            collection_jitter: ${_param:kubernetes_telegraf_agent_collection_jitter}
            flush_interval: ${_param:kubernetes_telegraf_agent_flush_interval}
            flush_jitter: ${_param:kubernetes_telegraf_agent_flush_jitter}
            precision: ${_param:kubernetes_telegraf_agent_precision}
            logfile: ${_param:kubernetes_telegraf_agent_logfile}
            debug: ${_param:kubernetes_telegraf_agent_debug}
            quiet: ${_param:kubernetes_telegraf_agent_quiet}
            omit_hostname: ${_param:kubernetes_telegraf_agent_omit_hostname}
        virtlet:
          enabled: ${_param:kubernetes_virtlet_enabled}
          namespace: kube-system
          image: ${_param:kubernetes_virtlet_image}
          criproxy_version: ${_param:kubernetes_criproxy_version}
          criproxy_source: ${_param:kubernetes_criproxy_checksum}
          use_apparmor: ${_param:kubernetes_virtlet_use_apparmor}
        metallb:
          enabled: ${_param:kubernetes_metallb_enabled}
          controller_image: ${_param:kubernetes_metallb_controller_image}
          speaker_image: ${_param:kubernetes_metallb_speaker_image}
        ingress-nginx:
          enabled: ${_param:kubernetes_ingressnginx_enabled}
          controller_image: ${_param:kubernetes_ingressnginx_controller_image}
          controller_replicas: ${_param:kubernetes_ingressnginx_controller_replicas}
    pool:
      enabled: false
      kubelet:
        fail_on_swap: ${_param:kubelet_fail_on_swap}
      container: false
      network:
        genie:
          enabled: ${_param:kubernetes_genie_enabled}
          source: ${_param:kubernetes_genie_source}
          source_hash: ${_param:kubernetes_genie_source_hash}
        calico:
          enabled: ${_param:kubernetes_calico_enabled}
          image: ${_param:kubernetes_calico_image}
          calicoctl_image: ${_param:kubernetes_calico_calicoctl_image}
          cni_image: ${_param:kubernetes_calico_cni_image}
          kube_controllers_image: ${_param:kubernetes_calico_kube_controllers_image}
        opencontrail:
          enabled: ${_param:kubernetes_opencontrail_enabled}
          cni_image: ${_param:kubernetes_contrail_cni_image}
        sriov:
          enabled: ${_param:kubernetes_sriov_enabled}
          source: ${_param:kubernetes_sriov_source}
          source_hash: ${_param:kubernetes_sriov_source_hash}
        flannel:
          enabled: ${_param:kubernetes_flannel_enabled}
