classes:
- system.linux.system.repo.mcp.apt_mirantis.saltstack
- system.linux.system.repo.mcp.extra
- system.openssh.client.root
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.cert.proxy
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.sphinx.server.doc.reclass
- cluster.try-mcp.cicd
parameters:
  linux:
    system:
      user:
        ubuntu:
          email: ubuntu@localhost
          enabled: true
          full_name: ubuntu
          home: /home/ubuntu
          name: ubuntu
          sudo: true
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
