classes:
- system.linux.system.repo.mcp.apt_mirantis.saltstack
- system.linux.system.repo.mcp.extra
- system.openssh.client.root
- system.salt.master.pkg
- system.salt.master.api
  # Temp disable
  #- system.salt.minion.cert.proxy
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.sphinx.server.doc.reclass
- cluster.try-mcp.cicd
parameters:
  salt:
    master:
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
  reclass:
    storage:
      class_mapping:
        aio_node:
          expression: all # only AIO node should be dynamically classified
          node_class:
            value_template:
              - cluster.<<node_cluster>>.openstack.aio
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
