parameters:
  _param:
    cluster_public_host: ${_param:single_address}
    cluster_domain: try-mcp.local
    cluster_name: try-mcp
    salt_minion_ca_authority: salt_master_ca
    linux_system_codename: xenial
    apt_mk_version: 2018.8
    infra_config_hostname: cfg01
    infra_config_address: ${_param:single_address}
    salt_minion_ca_host: cfg01.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca
    salt_api_password: fKbBBUNIhe45HUbYCSMbQyugcr9XcCgS
    salt_api_password_hash: "$6$patvcDfx$N33qHBU9F5e7N6V8ysYzp5IudOHBGyA/QH/WOqjAcdYDP9p5hCESsROrKJiKS8oosz67.LM5gpMmDytbnRmzD0"
    salt_master_base_environment: prd
    salt_master_host: ${_param:single_address}
    reclass_data_repository: "https://github.com/LotharKAtt/trymcp-drivetrain-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_address}
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
